const express = require('express');
const app = express();
const port = process.env.PORT || 4001;
const { createNodeLogger } = require('../../../tools/logging/node-logger');
const logger = createNodeLogger({ serviceName: 'jen1', logDir: process.env.LOG_DIR || 'tmp/logs/jen1' });

app.get('/', (req, res) => {
  res.json({ name: 'jen1', status: 'ready' });
});

app.get('/health', (req, res) => res.status(200).json({ status: 'ok' }));

// Minimal PoC generate endpoint - in production this would call a model runtime
app.post('/generate', express.json(), (req, res) => {
  const { narrative = '', duration = 30 } = req.body || {};
  // Return a deterministic, simple generated song JSON structure compatible with API
  const title = (narrative && narrative.split(/\.|,|\n/)[0]?.slice(0, 40)) || 'Untitled Jen1 Song';
  const lyrics = `Generated by jen1:\n${narrative || 'A gentle melody in the code'}\nChorus: Remember the harmony`;
  const song = {
    title,
    artist: 'jen1 (PoC) Composer',
    genre: 'pop',
    tempo: 120,
    time_signature: '4/4',
    key: 'C major',
    mood: 'energetic',
    instrumentation: ['piano', 'guitar', 'drums', 'lead_voice'],
    verse_1: {
      lyrics: lyrics.split('\n').slice(0, 3),
      chords: ['C', 'G', 'Am', 'F'],
    },
    chorus: {
      lyrics: ['Remember the harmony', 'Let the melody hold us'],
      chords: ['F', 'G', 'Em', 'Am'],
    },
    syllableCount: lyrics.split(/\s+/).length,
    wordCount: lyrics.split(/\s+/).length,
  };
  res.json(song);
});

app.listen(port, () => logger.info(`jen1 listening on ${port}`));
